### ISSUE TITLE
Teacher Interface

### ISSUE THREAD

**Issue by RHOMBI** [ZealussGaming/Hobsonville-point-selection-application#27]
@Rextilon @mygamelaggin @ZealussGaming 

It would be nice to start working on/have a html page for the teachers to use, we currently have our draft page for the students, but we are yet to create one for the teachers.

Correct me if im wrong @ZealussGaming, Griffin and jack G's roles need each other, and mine (jack F) and chris, we need to communicate with each other.

In simple, the html programmer will make the teacher interface,

teachers use their interface to create their classes - made by (griffin)?
classes are submitted to database - chris
database holds classes - jack f
classes are pulled from database - chris
students interact with classes on client site page - (griffin/eden)?

Then further functions will be available and more will happen etc

If nothing else is taken from this, it would be nice to have the html and js person create the teacher interface soon, (as it would appear the first step for testing) and then the php person working on linking this to the database person (myself).

It would be nice for myself to spend time with @ZealussGaming and @hyukjun1 when we have the time, as i am aware he is dependand on me at this stage.

Lastly, I feel we should all be more co ordinated, after personally reflecting it has become much more apparent to me, how much we actually depend on each other for this project, we should have a group discussion and more detailed clarification of roles first thing next week imo, its been a few weeks, and it would be good to structure what we are all doing, and when specific tasks need to be completed by.

**Comment by ZealussGaming** [comment]
In that case... 
@Rextilon and @canalmaster you are going to need to go through the process of designing and programming the markup for this page. This is actually a very good issue to get started on seeing how little there is left for you two to do on the student class selection page. 

Also I have previously made a [comment](https://github.com/ZealussGaming/Hobsonville-point-selection-application/issues/4#issuecomment-397851024) on the [Initial web app markup](https://github.com/ZealussGaming/Hobsonville-point-selection-application/issues/4), regarding creating the rest of the pages for the web application.

I suggest you use the forms and input tag. Links to some helpful resources below. If you need any more help to implement this come and talk on me.

https://www.w3schools.com/html/html_forms.asp
https://www.w3schools.com/html/html_form_elements.asp
https://www.w3schools.com/html/html_form_input_types.asp

**Comment by ZealussGaming** [comment]
Rextilon has started working on this.

**Comment by ZealussGaming** [comment]
@ALL Can someone working on this update your progress?
