### ISSUE TITLE
Add Header Bar

### ISSUE THREAD

**Issue by Rextilon** [ZealussGaming/Hobsonville-point-selection-application#29]
Create easy way for us to add the header bar to each page. @ZealussGaming

**Comment by ZealussGaming** [comment]
On it!

**Comment by ZealussGaming** [comment]
Done like, 4 weeks ago.

**Comment by ZealussGaming** [comment]
There is a headerBar.html code snippet found in the HTMLSnippets folder. It can be added to php files using 
`<?php 
		include ('HtmlSnippets/headerBar.html');		
	?>
`
