### ISSUE TITLE
Set up a database

### ISSUE THREAD

**Issue by ZealussGaming** [ZealussGaming/Hobsonville-point-selection-application#3]
Rhombi shall be in charge of organising and putting together a database to store the following: profiles, has to differentiate students and teachers; class details and descriptions; student selections, including whether they have been verified by their hub coaches; and a table for assigned classes.
The above conditions are not final however and can be structured however to what is deemed fit.

**Comment by RHOMBI** [comment]
Refined 2 databases on jacks login on the server 10.200.50.108, these are the classes and assessments tables, although i am yet to join the assesments with the classes @hyukjun1 @ZealussGaming @mygamelaggin , am still yet to find out about/create profiling, chosen classes, assigned classes/verity, @hyukjun1

**Comment by ZealussGaming** [comment]
If you feel confident about the structure you've laid out try extracting the necessary information, like user1's first module 1 choice, the subject of user3's 3rd spin2 choice, what module 2 first course is.
