### ISSUE TITLE
Home Pages for Teachers and Students separately.

### ISSUE THREAD

**Issue by Rextilon** [ZealussGaming/Hobsonville-point-selection-application#34]
We need to create a Home page for the Teachers and one for the Students that will display their classes that they have chosen it will also have links to the choose classes but I think they shouldn't be able to go to that page once they have chosen it. Both pages will need to have the header bar.
https://github.com/ZealussGaming/Hobsonville-point-selection-application/issues/29#issue
Also the Teacher interface is similar to this. Link below to that page.
https://github.com/ZealussGaming/Hobsonville-point-selection-application/issues/27#issue

**Comment by ZealussGaming** [comment]
There are two ways I can do it:
### Either with PHP:
```
<?php 
 include ('HtmlSnippets/headerBar.html');		
?>
```
### ...Or with JavaScript:
```
<div w3-include-html="headerBar.html"></div>

<script>
function includeHTML() {
  var z, i, elmnt, file, xhttp;
  /*loop through a collection of all HTML elements:*/
  z = document.getElementsByTagName("*");
  for (i = 0; i < z.length; i++) {
    elmnt = z[i];
    /*search for elements with a certain atrribute:*/
    file = elmnt.getAttribute("w3-include-html");
    if (file) {
      /*make an HTTP request using the attribute value as the file name:*/
      xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4) {
          if (this.status == 200) {elmnt.innerHTML = this.responseText;}
          if (this.status == 404) {elmnt.innerHTML = "Page not found.";}
          /*remove the attribute, and call this function once more:*/
          elmnt.removeAttribute("w3-include-html");
          includeHTML();
        }
      } 
      xhttp.open("GET", file, true);
      xhttp.send();
      /*exit the function:*/
      return;
    }
  }
}
</script>

<script>
includeHTML();
</script>
```

Although if I do do itin PHP, I'll need to convert your files to .php files so you'll need xampp. Also if the page needed to interact with the database then it need to be either way.
